# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Publish docs.k8ssandra-dev.io

on:
  push:
    branches: [ main ]

jobs:
  build_and_publish:
    name: Build and publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Checkout code w/ submodules
      with:
        submodules: recursive
    - uses: google-github-actions/setup-gcloud@master
      name: Setup gcloud
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
    - uses: actions/setup-node@v2
      name: Build and deploy
      with:
        node-version: 14.x
        cache: 'npm'
    - run: npm install
    - run: npm run build
    - run: npm run deploy:dev
